services:
  lighthouse-qa:
    build: .
    env_file:
      - .env
    environment:
      SAUCE_USERNAME: ${SAUCE_USERNAME}
      SAUCE_PASSWORD: ${SAUCE_PASSWORD}
      FLAKE_MODE: ${FLAKE_MODE:-false}
    volumes:
      - ./reports:/app/reports
      - ./playwright-report:/app/playwright-report